FROM docker.io/aussielunix/base:latest
RUN dnf -y install 'dnf-command(copr)' \
  && dnf -y copr enable @caddy/caddy \
  && dnf -y install \
    caddy \
  && dnf clean all \
  && rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} \
  && systemctl enable caddy
COPY website/ /usr/share/caddy/
