# :BUG: can not build Fedora40 iso installer
# https://github.com/osbuild/bootc-image-builder/issues/421
# FIXED upstream https://github.com/osbuild/images/pull/696
FROM quay.io/fedora/fedora-bootc:40
RUN dnf -y install \
    cloud-init \
    qemu-guest-agent \
    vim \
  && dnf clean all \
  && ln -s ../cloud-init.target /usr/lib/systemd/system/default.target.wants \
  && rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} \
  && systemctl enable qemu-guest-agent \
  && systemctl enable bootc-fetch-apply-updates.timer
