FROM quay.io/centos-bootc/centos-bootc:stream9
#FROM quay.io/fedora/fedora-bootc:40 https://github.com/osbuild/bootc-image-builder/issues/421

ARG sshpubkey
ARG newuser=lunix
ARG newuserpass=mynewpassword

COPY wheel-nopasswd /etc/sudoers.d

RUN if test -z "$sshpubkey"; then echo "must provide sshpubkey"; exit 1; fi; \
    useradd -m -s /bin/bash -G wheel -U $newuser && \
    echo ${newuser}:${newuserpass} | chpasswd && \
    mkdir -m 0700 -p /home/$newuser/.ssh && \
    echo $sshpubkey > /home/$newuser/.ssh/authorized_keys && \
    chmod 0600 /home/$newuser/.ssh/authorized_keys && \
    chown -R $newuser: /home/$newuser
RUN dnf -y install mc NetworkManager-wifi NetworkManager-wwan wpa_supplicant wireless-regdb && dnf clean all

