# :BUG: can not build Fedora40 iso installer
# https://github.com/osbuild/bootc-image-builder/issues/421
# FIXED upstream https://github.com/osbuild/images/pull/696
FROM quay.io/fedora/fedora-bootc:40
RUN dnf install -y --nobest \
    --excludepkgs rootfiles,firefox,gnome-tour \
    '@Fedora Workstation' \
    'flatpak' \
    'flatpak-spawn' \
    'flatseal' \
    'terminator' \
    'distrobox' \
    'gnome-extensions-app' \
    'gnome-shell-extension-appindicator' \
    'gnome-tweaks' \
    'strace' \
    'wl-clipboard' \
    'wireguard-tools' \
    'vim-enhanced' \
  && dnf remove -y \
    'passim' \
    'tracker' \
    'tracker-miners' \
  && dnf clean all \
  && rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} \
  && flatpak remote-add --system --if-not-exists --subset=verified flathub-verified https://flathub.org/repo/flathub.flatpakrepo \
  && systemctl enable qemu-guest-agent \
  && systemctl enable bootc-fetch-apply-updates.timer \
  && systemctl disable ModemManager.service \
  && systemctl disable cups.service
COPY system_files /
